app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - ${PUBLIC_URL}
  mp:
    # URL pública necesaria para que Mercado Pago pueda acceder al endpoint de callback
    # Puede utilizarse ngrok u otra herramienta de túnel
    redirect-uri: ${PUBLIC_URL}/mp/callback
  api:
    uri: http://localhost:8080